### PR TITLE
#596 : Fix class-name rule conversion

### LINKED ISSUE #596: class-name convert deprecated. Rename to naming-convention
It's ot actually missing, but rule name is out of date.
[typescript-eslint issue with explaination](https://github.com/typescript-eslint/typescript-eslint/issues/1854#issuecomment-609913921)
I've a PR, so you can let me know when you accept it and I'll submit.

### 💥 Missing Converter

-   `tslint-to-eslint-config` version: latest
-   `typescript-eslint` version: 3.0.2

#### TSLint Rule Name

**class-name**

### PR DESCRIPTION
**Pull request by GrzesiekP**
## PR Checklist

-   [✅ ] Addresses an existing issue: fixes #596 
-   [✅ ] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

output rule name is changed according to changes in typescript-eslint

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Relevant: https://github.com/typescript-eslint/typescript-eslint/blob/d514d41a756018ccc51b4b862e056d18e8490305/packages/eslint-plugin/docs/rules/class-name-casing.md, https://github.com/typescript-eslint/typescript-eslint/pull/1318/

We'll want to check how the default configuration for the rule has changed, if at all.

**Comment by KingDarBoja** [comment]
Several rules were removed and simplified into this one so we should cover those as well.
Jump to [rule removals](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) section to see those listed.

**Comment by GrzesiekP** [comment]
> Several rules were removed and simplified into this one so we should cover those as well.
> Jump to [rule removals](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) section to see those listed.

Ok. Should I make changes for other rules in this PR?

**Comment by JoshuaKGoldberg** [comment]
Yes please @GrzesiekP! Let us know if you'd like a spot check or help creating the rule changes. I'm finding it hard to find documentation for what the exact changes were so this might be a little hard. 😦

**Comment by KingDarBoja** [comment]
I think @GrzesiekP went missing in action (😆) so probably taking this one.

**Comment by KingDarBoja** [comment]
Closing as this will require extra work (a merger).

**Pull request closed without merging**
