### PR TITLE
Update CircleCI with current tag

### PR DESCRIPTION
**Pull request by KingDarBoja**
## Overview

The build is failing and no clue why 😭 This is a test PR to see if the build is triggered.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Seems like it is working now: https://app.circleci.com/pipelines/github/typescript-eslint/tslint-to-eslint-config

**Comment by JoshuaKGoldberg** [comment]
Yeah these failures are very weird... https://app.circleci.com/pipelines/github/typescript-eslint/tslint-to-eslint-config/2129/workflows/2a9faca7-bead-4208-a89e-1780258d19ce/jobs/10946

```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.20.1
Cloning git repository
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
remote: Enumerating objects: 6220, done.        
remote: Counting objects: 100% (923/923), done.        
remote: Compressing objects: 100% (477/477), done.        
remote: Total 6220 (delta 667), reused 655 (delta 438), pack-reused 5297        
Receiving objects: 100% (6220/6220), 3.35 MiB | 47.04 MiB/s, done.
Resolving deltas: 100% (4753/4753), done.
Checking out branch
fatal: reference is not a tree: cbb9b99748fe00b4f55152f2d9d441142b159e57

exit status 128
CircleCI received exit code 128
```

**Comment by JoshuaKGoldberg** [comment]
Well, I guess it was a CircleCI outage of some kind? I'll close this for now to keep the queue small. 🤷 

Thanks for looking!

**Comment by KingDarBoja** [comment]
No worries, glad everything is working again 🚀

**Pull request closed without merging**
